### ISSUE TITLE
Please add your grid.js library to the Bower repository.

### ISSUE THREAD

**Issue by himiklab** [openpsa/grid.js#20]

**Comment by meh-uk** [comment]
How do we do that?

**Comment by himiklab** [comment]
now http://bower.io/search/?q=grid.js

**Comment by flack** [comment]
@meh-uk here's a how-to:

http://bower.io/docs/creating-packages/#register

But I'm not sure if we shouldn't do a release first. I mean, right now, we have practically no documentation and we're still kind of deciding on the direction of the development. But I guess we could just write a disclaimer about that somewhere

**Comment by meh-uk** [comment]
Can we change the version to 0.1 or something?

**Comment by flack** [comment]
would be fine by me. Not sure what the others think of that though

**Comment by meh-uk** [comment]
OK I've registered the project as `grid.js` in the bower repository - although nothing is available yet as we haven't created any tagged release versions.
