### ISSUE TITLE
LESS or not

### ISSUE THREAD

**Issue by bouks** [openpsa/grid.js#35]
This question has been asked several times in different places, so i propose we discuss it and vote here to close the question.

I vote for less.

**Comment by kirilvit** [comment]
+1 
I vote for less.

**Comment by meh-uk** [comment]
I haven't used it much but I had a quick play at the weekend. It looks much better than CSS which has always become a mess in my experience.

I vote for less

**Comment by flack** [comment]
Alright, then I guess it is decided. LESS wins 4:0. Closing the ticket.
