### ISSUE TITLE
Rendering glitches in search toolbar demo 

### ISSUE THREAD

**Issue by flack** [openpsa/grid.js#51]
See the following screenshot:

![bildschirmfoto 2015-01-13 um 20 27 54](https://cloud.githubusercontent.com/assets/425166/5727377/dd9f4d06-9b62-11e4-9e3c-d220dafbf106.png)

Taken with Firefox 34 on Mac OS 10.9 on http://openpsa.github.io/grid.js/demos/searchFilterOperator.html

Additionally, if you hover over the icon next to the search input, the tooltip says `undefined`.

**Comment by bouks** [comment]
And in Firefox 35 ? :)

**Comment by bouks** [comment]
I have the same problem on the demo on windows. But not with my grid version (that is before oleg's commits merging).

But we should probably redesign sopt_menu and these f.... neolithic HTML tables. :)

**Comment by meh-uk** [comment]
I had that issue yesterday with Safari 8 on Mac OS X 10.10.

**Comment by bouks** [comment]
@meh-uk I had that issue with lynx. :D

**Comment by bouks** [comment]
I'll fix it today.

**Comment by bouks** [comment]
The fix is done. Waiting build to close.

**Comment by flack** [comment]
Verified fixed. Thanks!

**Comment by flack** [comment]
P.S.: I still get `undefined` as tooltip, though

**Comment by flack** [comment]
See here:

![tooltip](https://cloud.githubusercontent.com/assets/425166/5739682/7f8ac764-9bfc-11e4-8a23-28b47bb3c493.png)

Taken on Kubuntu with Firefox 34 (the mouse is hovering over the expand icon)
