### ISSUE TITLE
Clear Search Value button does not appear in the filter toolbar.

### ISSUE THREAD

**Issue by himiklab** [openpsa/grid.js#76]

**Comment by flack** [comment]
Seems to be a css problem. The button is there in the DOM, but it's not displayed because the input field pushes it out of the visible area. @bouks is this due to a merge issue with Oleg's code or did it happen in your original modification as well?

**Comment by bouks** [comment]
Fixed in PR :
https://github.com/openpsa/grid.js/pull/74

(the dist js files are not yet updated)

**Comment by bouks** [comment]
Fixed here :
https://github.com/openpsa/grid.js/commit/4f86672e6ed0c0cd6f7e749c58f35e0a9fbb0595

**Comment by bouks** [comment]
Partially fixed.

Depends on https://github.com/openpsa/grid.js/issues/81 to close

**Comment by flack** [comment]
Completely fixed now. thanks for the report, @himiklab
